// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int greater = 0;
		int smallerEq = 0;
		for (int i = 0; i < N; i++) {
			double x = Math.random();
			if (x >= 0.5) {
				greater++;
			} else {
				smallerEq++;
			}
		}
		System.out.println("> 0.5:  " + smallerEq);
		System.out.println("<= 0.5: " + greater);
		if (smallerEq == 0) {
			return;
		}
		double ratio = (double) greater / smallerEq;
		System.out.println("Ratio:  " + ratio);
	}
}
